server.port=${SERVER_PORT:8081}
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:postgres}:${POSTGRES_PORT:5432}/${POSTGRES_DB:cinevision}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${POSTGRES_USER:cinevision_movie_app}
spring.datasource.password=${POSTGRES_PASSWORD:movie_app_password_change_me}
spring.data.redis.host=${REDIS_HOST:redis}
spring.data.redis.port=${REDIS_PORT:6379}
spring.redis.timeout=${SPRING_REDIS_TIMEOUT:30s}
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
spring.kafka.topic.name=${KAFKA_EMAIL_TOPIC:email-topics}
management.zipkin.tracing.endpoint=http://${ZIPKIN_HOST:zipkin}:${ZIPKIN_PORT:9411}/api/v2/spans
eureka.client.service-url.defaultZone=http://${EUREKA_USERNAME:eureka}:${EUREKA_PASSWORD:password}@${EUREKA_HOST:eureka-server}:${EUREKA_PORT:8761}/eureka/
