server.port=${SERVER_PORT:8083}
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
spring.kafka.consumer.group-id=${KAFKA_EMAIL_GROUP:email-service}
spring.kafka.topic.name=${KAFKA_EMAIL_TOPIC:email-topics}
spring.mail.host=${MAIL_HOST:mailhog}
spring.mail.port=${MAIL_PORT:1025}
management.zipkin.tracing.endpoint=http://${ZIPKIN_HOST:zipkin}:${ZIPKIN_PORT:9411}/api/v2/spans
eureka.client.service-url.defaultZone=http://${EUREKA_USERNAME:eureka}:${EUREKA_PASSWORD:password}@${EUREKA_HOST:eureka-server}:${EUREKA_PORT:8761}/eureka/
