apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cinevision-prod
nameSuffix: -blue
labels:
  - pairs:
      track: blue
    includeSelectors: true
resources:
  - ../../../base
  - gateway.yaml
  - virtualservice.yaml
  - destinationrule.yaml
images:
  - name: api-gateway
    newName: ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/cinevision/api-gateway
    newTag: latest
  - name: user-service
    newName: ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/cinevision/user-service
    newTag: latest
  - name: movie-service
    newName: ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/cinevision/movie-service
    newTag: latest
  - name: email-service
    newName: ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/cinevision/email-service
    newTag: latest
  - name: eureka-server
    newName: ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/cinevision/eureka-server
    newTag: latest
  - name: frontend
    newName: ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/cinevision/frontend
    newTag: latest
patches:
  - path: configmap-patch.yaml
  - path: externalsecret-patch.yaml
  - path: secretstore-patch.yaml
