apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: cinevision-secret-store
spec:
  provider:
    aws:
      auth:
        jwt:
          serviceAccountRef:
            name: cinevision-secrets-sa-blue
            namespace: cinevision-prod
