apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretsmanager
spec:
  provider:
    aws:
      auth:
        jwt:
          serviceAccountRef:
            name: cinevision-secrets-sa-blue
