server.port=${SERVER_PORT:8080}
eureka.client.service-url.defaultZone=http://${EUREKA_USERNAME:eureka}:${EUREKA_PASSWORD:password}@${EUREKA_HOST:eureka-server}:${EUREKA_PORT:8761}/eureka/
management.zipkin.tracing.endpoint=http://${ZIPKIN_HOST:zipkin}:${ZIPKIN_PORT:9411}/api/v2/spans
