server.port=${SERVER_PORT:8080}
spring.application.name=api-gateway
eureka.client.service-url.defaultZone=http://${EUREKA_USERNAME:eureka}:${EUREKA_PASSWORD:password}@${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
eureka.instance.prefer-ip-address=true
spring.cloud.gateway.routes[0].id=movie-service
spring.cloud.gateway.routes[0].uri=lb://movie-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/movie/**
spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=lb://user-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/user/**
spring.cloud.gateway.routes[2].id=eureka-ui
spring.cloud.gateway.routes[2].uri=http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}
spring.cloud.gateway.routes[2].predicates[0]=Path=/eureka/web
spring.cloud.gateway.routes[2].filters[0]=SetPath=/
spring.cloud.gateway.routes[3].id=eureka-static
spring.cloud.gateway.routes[3].uri=http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}
spring.cloud.gateway.routes[3].predicates[0]=Path=/eureka/**
spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_UNIQUE
spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origin-patterns=${CORS_ALLOWED_ORIGINS:*}
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}/api/v2/spans
logging.level.root=INFO
