apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cinevision-app-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cinevision-secret-store
    kind: ClusterSecretStore
  target:
    name: cinevision-app-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  dataFrom:
    - extract:
        key: /cinevision/dev/application-secrets
