apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: cinevision-gateway
spec:
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "dev.cinevisionca.link"
    - "api.dev.cinevisionca.link"
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: cinevision-tls
    hosts:
    - "dev.cinevisionca.link"
    - "api.dev.cinevisionca.link"
