apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: cinevision-secret-store
spec:
  provider:
    aws:
      auth:
        jwt:
          serviceAccountRef:
            namespace: cinevision-dev
